"""Generate /search/index.html and the taxonomy half of the search index.

The brief asks search to cover articles, countries, regions and topics. Article
search already existed; this adds the ~290 taxonomy entries so typing "Nigeria"
finds West Africa and "gulf" finds the Gulf subregion.

Countries are indexed to their subregion page anchor, not to a page of their
own, so a search hit always lands on real content.
"""
import sys, os, json
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import gen_nav as N
from gen_page import render, emit
from gen_lib import ROOT, esc, write

OUT_INDEX = "/assets/js/taxonomy-index.js"

entries = []


def add(title, url, kind, sub):
    entries.append({"t": title, "u": url, "k": kind, "s": sub})


g = N.TOPICS["global"]
add(g["name"], g["path"], "section", "Global")
for c in g["children"]:
    add(c["name"], f'{g["path"]}{c["slug"]}/', "section", "Global")

for r in N.REGIONS:
    add(r["name"], r["path"], "region", "Region")
    for s in r["sections"]:
        # A flat region has no subregion page, so its countries must index
        # against the region page -- which is where their anchors now live.
        if r.get("flat"):
            for c in s["countries"]:
                add(c["name"], f'{r["path"]}#{c["anchor"]}', "country", r["name"])
            continue
        base = f"/geopolitics/{r['slug']}/{s['slug']}/"
        add(s["name"], base, "subregion", r["name"])
        for c in s["countries"]:
            add(c["name"], f"{base}#{c['anchor']}", "country", s["name"])

for slug in ("markets", "macro", "research", "blog"):
    t = N.TOPICS[slug]
    add(t["name"], t["path"], "section", t["name"])
    for c in t["children"]:
        add(c["name"], f'{t["path"]}{c["slug"]}/', "section", t["name"])

# ---- JS index ---------------------------------------------------------------
# A plain script rather than fetch() of a JSON file: one fewer request, and it
# works from file:// as well as over HTTP. search.js falls back to fetch() so a
# future server-side index can replace this file without touching the UI.
js = ("/* Y-Squre - taxonomy search index. GENERATED by gen_search.py - do not edit.\n"
      "   %d entries: regions, subregions, countries, topics. */\n"
      "window.YSQ_TAXONOMY = %s;\n" % (len(entries), json.dumps(entries, ensure_ascii=False)))
write(OUT_INDEX, js)

# ---- the page ---------------------------------------------------------------
children = []
for c in entries:
    if c["k"] in ("region", "section"):
        children.append(f'      <li><a href="{c["u"]}">{esc(c["t"])}</a>'
                        f'<span class="sug-kind">{esc(c["s"])}</span></li>')

body = '''  <main id="main" class="wrap page">
    <nav class="crumbs" aria-label="Breadcrumb"><ol>
      <li><a href="/latest/">Home</a></li>
      <li><span aria-current="page">Search</span></li>
    </ol></nav>
    <h1>Search</h1>
    <p class="page-lede">Search articles, regions, subregions, countries and
    topics. Everything is matched on Y-Squre's own index; nothing is sent to
    a third party.</p>

    <form class="search-page-form" id="search-form" role="search" method="get" action="/search/">
      <label class="sr-only" for="search-input">Search Y-Squre</label>
      <input type="search" id="search-input" name="q" autocomplete="off"
             spellcheck="false" placeholder="Nigeria, Gulf, inflation, currency&hellip;">
      <button type="submit">Search</button>
    </form>
    <p class="search-count" id="search-count"></p>
    <div id="search-results" class="search-results"></div>

    <h2 class="section-h">Browse by region</h2>
    <ul class="link-list">
''' + "\n".join(children) + '''
    </ul>
  </main>
'''

page = {
    "path": "/search/index.html",
    "url": "/search/",
    "title": "Search | Y-Squre",
    "desc": ("Search Y-Squre across articles, regions, subregions, countries "
             "and topics."),
    "h1": "Search",
    "body": body,
    "section": "search",
    "extra_css": ("/assets/css/search.css",),
}

if __name__ == "__main__":
    emit([page])
    print(f"  {len(entries)} taxonomy search entries -> {OUT_INDEX}")
    print(f"  search page -> /search/index.html")
    by_kind = {}
    for e in entries:
        by_kind[e["k"]] = by_kind.get(e["k"], 0) + 1
    print("  " + "  ".join(f"{k}={v}" for k, v in sorted(by_kind.items())))
